config/routes.rb
Rails.application.routes.draw do
  get 'heros/new'

  get 'heros/create'

  get 'heros/show'

  root 'categories#index'

  get     'signup'  => 'users#new'
  get     'login'   => 'sessions#new'
  post    'login'   => 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :users
  resources :categories
  resources :actors
  resources :heros

end

app/views/layouts/_cloud.html.haml
%h2 Parts
%ul.tag-cloud
  <li><a href="" rel="tag" class="w2">Hairstyles</a></li>
  <li><a href="" rel="tag" class="w8">Lipsticks</a></li>
  <li><a href="" rel="tag" class="w3">Glasses</a></li>
  <li><a href="" rel="tag" class="w4">Eyebrows</a></li>
  <li><a href="" rel="tag" class="w5">Blushers</a></li>
  <li><a href="" rel="tag" class="w6">Eyeshadows</a></li>
  <li><a href="" rel="tag" class="w7">Eyeliners</a></li>
  <li><a href="" rel="tag" class="w9">Eyelashes</a></li>
  <li><a href="" rel="tag" class="w1">Jewelry</a></li>
  <li><a href="" rel="tag" class="w3">Contact lenses</a></li>

app/views/layouts/_menuItem.html.haml
- label, path, html_options, hide = *menuItem
- if !hide
  - html_options ||= {}
  - if current_page?(path)
    - html_options.merge! :class => 'current' 
  %li= link_to label, path, html_options

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Makeup Room
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

 
  %body
    %header
      %h1.title Makeup Room
    #navigation
      #tabs
        %ul
          = render :partial => 'layouts/menuItem', :collection => [ |
            ['Home', root_path]     |        
          ] |
          %div{'style' => "float: right;"}
            - if !logged_in?
              = render :partial => 'layouts/menuItem', :collection => [ |
                ['Login', 'login'],                      |
                ['Sign up', signup_path]            |
              ] |
            - else
              = render :partial => 'layouts/menuItem', :collection => [ |
                ['Work', '#'],         |
                ['Actor', new_actor_path],         |
                ['Hero', new_hero_path],         |
                ['Logout', logout_path, method: "delete"]         |
              ] |
              - 
              %div{'style' => "float: right;"}
                -#= render :partial => 'layouts/menuItem', :collection => [               |
                -#['Accounts', accounts_path],     |
                -#['Projects', projects_path],     |
                -#['Activities', activities_path], |
                -#['Leads', leads_path],            |
                -#['Expenses', expenses_path],            |
                  -#['Your profile', profile_path],                               |
                  -#['Admin settings', settings_path, nil, !current_user.admin?], |
                  -#['Logout', user_session_path, { :method => :delete }]         |
                ] |
              -
              
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
      - elsif flash[:success]
        #warning.message= flash[:success]
      #container
        = yield
    #aside
      #section
        %h2 Tools
        %input.testImg#getPhoto{:type => "file"} 
        %button#getActor Upload Actor      
      #section
        = render :partial => 'layouts/cloud'
    #footer
      &nbsp;
      4U 2016
      #container
        #nav
          %ul{:class => "nav navbar-nav navbar-right dropdown"}
            - if logged_in?
              %li
                = link_to "Users", users_path
              %li{:class => "dropdown"}
                %a{:href => "#", :class => "dropdown-toggle", 'data-toggle' => "dropdown"}
                  Account 
                  %b{:class =>"caret"}
                %ul{:class => "dropdown-menu"}
                  %li
                    = link_to "Profile", current_user
                  %li
                    = link_to "Settings", edit_user_path(current_user) 
                  %li{:class => "divider"}
                  %li
                    = link_to "Log out", logout_path, method: "delete"
            - else 
              %li
                = link_to "Log in", login_path
    = debug(params) if Rails.env.development?  
    
  